version: "3.9"
services:
  agent:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./logs:/home/appuser/logs
      - ./data:/home/appuser/data
    command: python agent.py
    restart: unless-stopped